/**
 * Short client-facing descriptions (at most 6 words), keyed by catalog dish name.
 * Only used on proposal menus. The seed test checks every dish has one.
 */
export const DESCRIPTIONS: Record<string, string> = {
  // ---- Breakfast ----
  'Fresh Baked Pastries': 'Croissants, danishes and muffins, baked daily',
  'Fresh Bagels and Cream Cheese': 'Local bagels with whipped spreads',
  'Organic Scrambled Eggs': 'Soft, fluffy farm-fresh eggs',
  'Tofu Scramble': 'Turmeric-spiced tofu with sautéed vegetables',
  'Local Sausage with Thyme': 'Savory pork sausage with fresh thyme',
  'Assorted Burritos': 'Eggs, cheese and fillings, warmly wrapped',
  'Maple Bacon': 'Thick-cut bacon glazed with maple',
  'Cinnamon Pancakes': 'Fluffy stacks swirled with cinnamon sugar',
  'Huevos Rancheros': 'Fried eggs, ranchero salsa, warm tortillas',
  'Hash Brown Potatoes': 'Golden, crispy shredded potatoes',
  'Signature Crumb Cakes': 'Buttery cake with brown-sugar crumble',
  'Scrambled Organic Eggs': 'Soft, fluffy farm-fresh eggs',
  '“Just” Eggs Scrambled': 'Plant-based eggs, scrambled soft',
  'Hard Boiled Eggs': 'Simple, protein-rich and perfectly cooked',
  'Egg Station': 'Eggs and omelets made to order',
  'Shakshuka': 'Eggs poached in spiced tomato sauce',
  'Crispy Bacon': 'Smoky, perfectly crisp strips',
  'Canadian Bacon': 'Lean, gently smoked back bacon',
  'Local Sausage Patties': 'Savory, herb-seasoned breakfast patties',
  'Local Sausage Links': 'Classic seasoned breakfast links',
  'Local Turkey Sausage Patties': 'Lean turkey, sage and pepper',
  'Vegan Sausage': 'Plant-based, savory and herb-seasoned',
  'Breakfast Potatoes': 'Roasted potatoes with peppers and onions',
  'Organic Home Fries': 'Pan-crisped potatoes with onions',
  'Blueberry Pancakes': 'Fluffy pancakes bursting with blueberries',
  'Buttermilk Pancakes with Warm Syrup': 'Classic golden stacks, warm syrup',
  'French Toast': 'Brioche dipped in vanilla custard',
  'Croissants with Ham and Cheese': 'Flaky croissants, ham and Gruyère',
  'Breakfast Burritos': 'Eggs, cheese and fillings, warmly wrapped',
  'Quinoa Cakes': 'Crispy, herbed quinoa patties',
  'Baked Beans': 'Slow-baked beans in tomato sauce',
  'Grilled Tomatoes': 'Charred tomatoes with herbs',
  'Hot Oatmeal': 'Creamy oats with seasonal toppings',
  'Assorted Fresh Bagels': 'Local bagels, never frozen',
  'Assorted Cream Cheese Selections': 'Plain, flavored and light spreads',
  'Lox with Capers, Crème Fraiche, Onions': 'Smoked salmon with classic garnishes',
  'Assorted Jellies, Jams, Preserves': 'Sweet fruit spreads for toast',
  'Peanut, Cashew and Almond Butter': 'Creamy nut butters, three ways',
  'Individual Assorted Cereals, Muesli, Granola': 'Crunchy cereals, muesli and granola',
  'Selection of Sliced Breads': 'Freshly sliced breads for toasting',
  'Selection of Greek and Plain Yogurts': 'Creamy Greek and plain yogurts',
  'Plain Yogurts': 'Smooth, creamy and simple',
  'Fresh Fruits': 'Seasonal fruit, freshly cut',

  // ---- Beverage / Service ----
  'Espresso Bar': 'Espresso, cappuccino and lattes',
  'Freshly Brewed Colombian Coffee': 'Rich coffee, regular and decaf',
  'Assorted Juices': 'Chilled orange, apple and more',
  'Selection of Milks and Non-Dairy': 'Dairy, oat, almond and soy',

  // ---- Soup ----
  'Tomato and Rice Soup': 'Hearty tomato broth with rice',
  'Lentil Soup': 'Hearty lentils simmered with vegetables',
  'Moroccan Lentil Soup': 'Lentils with warm North African spices',
  'Mulligatawny Soup': 'Curried lentil and vegetable soup',
  'Tuscan White Bean Soup': 'Cannellini beans, garlic and rosemary',
  'Tomato Cheddar Soup': 'Velvety tomato with sharp cheddar',
  'Ten Vegetable Soup': 'Garden vegetables in light broth',
  'Chicken Soup with Vegetables': 'Comforting broth, chicken and vegetables',
  'Autumn Minestrone': 'Italian vegetable soup with beans',
  'Black Bean Soup': 'Smoky black beans with cumin',
  'Broccoli Cheddar Soup': 'Creamy broccoli with sharp cheddar',
  'Butternut Squash Soup': 'Silky roasted squash, warming spices',
  'Carrot Ginger Soup': 'Sweet carrots with fresh ginger',
  'Carrot, Ginger & Artichoke Soup': 'Carrot, ginger and tender artichoke',
  'Chicken Corn Soup': 'Chicken and sweet corn chowder',
  'Cream of Broccoli Soup': 'Smooth, creamy broccoli soup',
  'Cream of Mushroom Soup': 'Earthy mushrooms in velvety cream',
  'French Onion Cheddar Soup': 'Caramelized onions under melted cheddar',
  'Lobster Bisque': 'Rich, creamy lobster soup',
  'Home Made Matzo Ball Soup': 'Fluffy matzo balls, golden broth',
  'Miso Soup with Tofu and Scallions': 'Savory miso, silken tofu, scallions',
  'Mushroom Barley Soup': 'Earthy mushrooms with hearty barley',
  'Pumpkin Bisque': 'Silky pumpkin with autumn spices',
  'Split Pea Soup': 'Thick, hearty split pea classic',
  'Sweet Cherry Tomato Soup': 'Bright, sweet cherry tomato purée',
  'Texas Chili': 'Spiced beef chili, Texas style',

  // ---- Sandwich ----
  'Mini Grilled Cheese Sandwiches on Country Bread': 'Golden, melty bites on country bread',
  'Aged Cheddar and Chutney': 'Sharp cheddar with sweet chutney',
  'Applewood Smoked Ham and Mustard': 'Smoked ham with grainy mustard',
  'Arugula, Parmesan, Pine Nuts, Balsamic': 'Peppery arugula, parmesan, toasted pine nuts',
  'Avocado & Parmesan': 'Creamy avocado with shaved parmesan',
  'Balsamic Chicken & Avocado': 'Balsamic chicken with ripe avocado',
  'BLT': 'Bacon, lettuce and ripe tomato',
  'Crispy Chicken Cutlet': 'Golden cutlet with crisp lettuce',
  'Chicken, Apple and Cranberry': 'Chicken salad with apple, cranberry',
  'Classic Turkey Club': 'Triple-decker turkey, bacon, tomato',
  'Green Goddess': 'Fresh vegetables with herby dressing',
  'Country Grilled Cheese': 'Melted cheese on toasted country bread',
  'Grilled Veggie Wrap': 'Charred vegetables in a soft wrap',
  'Homemade Falafel Wraps': 'Crispy falafel, tahini, fresh vegetables',
  'Spinach & Parmesan': 'Baby spinach with shaved parmesan',
  'Tuna Wraps': 'Albacore tuna salad, crisp greens',
  'Turkey and Mustard': 'Sliced turkey with Dijon mustard',
  'Turkey, Avocado on Pita': 'Turkey and avocado in warm pita',
  'Turkey Wraps': 'Sliced turkey, greens, soft wrap',

  // ---- Salad ----
  'Salad World': 'Build-your-own salad, organic vegetables',
  'Fresh Salad Bar Medley': 'Fresh greens and garden toppings',
  'Tuna, Chicken and Egg Salad': 'Three classic homemade salads',
  'Homemade Albacore Tuna, Chicken, Home-style Potato & Egg Salad': 'Classic homemade deli salads',
  'Mediterranean Salad': 'Tomato, cucumber, olives, herbs',
  'Baby Spinach Salad': 'Tender spinach with light vinaigrette',
  'Burrata Salad': 'Creamy burrata, tomatoes and basil',
  'Chickpea Salad': 'Chickpeas, herbs and lemon',
  'Cobb Salad': 'Chicken, bacon, egg, avocado, blue cheese',
  'Cole Slaw': 'Crisp cabbage in creamy dressing',
  'Grilled Chicken Caesar': 'Romaine, parmesan, croutons, grilled chicken',
  'Grilled Chicken, Spinach and Pine Nuts': 'Grilled chicken, spinach, toasted pine nuts',
  'Hummus and Grilled Veggies': 'Creamy hummus with charred vegetables',
  'Mesclun with Cranberries, Candied Walnuts and Blue Cheese': 'Greens, cranberries, walnuts, blue cheese',
  'Mesclun with Oranges, Apples and Nuts': 'Greens with citrus, apple, nuts',
  'Mixed Seasonal Greens': 'Fresh seasonal greens, light vinaigrette',
  'Pasta Primavera (cold)': 'Chilled pasta with spring vegetables',
  'Quinoa Salad with Mint': 'Fluffy quinoa, fresh mint, lemon',
  'Roasted Corn Salad': 'Charred corn, peppers and lime',
  'Three Bean Salad': 'Three beans in tangy vinaigrette',
  'Yellow and Red Beet Salad': 'Roasted golden and red beets',

  // ---- Pasta ----
  'Lasagna Bolognese': 'Layered pasta, rich meat ragù',
  'Penne alla Vodka': 'Penne in creamy tomato-vodka sauce',
  'Ricotta Ravioli with Toasted Sage': 'Ricotta ravioli, brown butter, sage',
  'Sesame Noodles': 'Chilled noodles in sesame dressing',
  'Vegetable Lo-Mein': 'Wok-tossed noodles with vegetables',
  'Stir Fry Noodles with Tofu': 'Wok noodles with crispy tofu',
  '5 Cheese Jalapeño Mac and Cheese': 'Five cheeses with a jalapeño kick',
  'Five Cheese Mac and Cheese': 'Creamy, baked five-cheese classic',
  'Penne al Pomodoro': 'Penne in fresh tomato basil sauce',
  'Rigatoni with Sausage and Peas': 'Rigatoni, sweet sausage, green peas',
  'Spaghetti Aglio e Olio': 'Garlic, olive oil and chili flakes',
  'Fettuccine Alfredo': 'Silky parmesan cream sauce',
  'Home Made Lasagna': 'Layers of pasta, sauce and cheese',
  '3 Cheese Ravioli with Sage Butter': 'Three-cheese ravioli in sage butter',
  'Alfredo Penne with Shitake Mushrooms and Parsley': 'Creamy penne with shiitake mushrooms',
  'Baby Spinach Lasagna': 'Spinach and ricotta layered lasagna',
  'Asiago Rigatoni': 'Rigatoni in nutty Asiago cream',
  "Bucatini All'Amatriciana": 'Pancetta, tomato and chili',
  'Cheese Ravioli with Saffron': 'Cheese ravioli in saffron cream',
  'Cheese Tortellini with Fresh Tomato and Basil': 'Tortellini, fresh tomato and basil',
  'Fettuccine with Creamy Rosemary Sauce': 'Fettuccine in rosemary cream sauce',
  'Fettuccine ai Porcini': 'Fettuccine with earthy porcini mushrooms',
  'Fresh Spinach and Chicken Ravioli with Organic Kale Pesto': 'Chicken ravioli with kale pesto',
  'Lobster Ravioli': 'Lobster-filled ravioli in light cream',
  'Manicotti with Ricotta and Tomato Sauce': 'Ricotta-stuffed shells, tomato sauce',
  'Orecchiette with Broccoli Rabe': 'Little ears with garlicky broccoli rabe',
  'Orecchiette with Organic Peas and Sausage': 'Orecchiette, sausage and sweet peas',
  'Organic Grilled Veggie Lasagna': 'Grilled vegetables layered with ricotta',
  'Penne with Chicken & Mushroom': 'Penne, chicken and sautéed mushrooms',
  'Penne with Eggplant & Tomato': 'Penne, roasted eggplant, tomato sauce',
  'Pesto Lasagna': 'Basil pesto layered with ricotta',
  'Radicchio & Ricotta Lasagna': 'Radicchio and ricotta layered lasagna',
  'Rigatoni with Bolognese Sauce': 'Rigatoni in slow-cooked meat sauce',
  'Shrimp Pad Thai': 'Rice noodles, shrimp, peanuts, lime',
  'Spaghetti alla Carbonara': 'Egg, pecorino, pancetta and pepper',
  'Spaghetti and Meatballs': 'Classic spaghetti with tender meatballs',

  // ---- Rice / Grains ----
  'Organic Yellow Rice with Vegetables': 'Saffron-hued rice with garden vegetables',
  'Faux Chorizo Paella': 'Saffron rice with plant-based chorizo',
  'Wild Rice Pilaf with Vegetable Medley': 'Nutty wild rice, mixed vegetables',
  'Jasmine Rice with Cranberries, Tofu and Dill': 'Jasmine rice, cranberries, tofu, dill',
  'Yellow Rice with Vegetables': 'Golden rice with mixed vegetables',
  'Steamed Jasmine Rice': 'Fragrant, fluffy jasmine rice',
  'Steamed White Rice': 'Simple, fluffy steamed rice',
  'Basmati Rice with Vermicelli': 'Basmati with toasted vermicelli noodles',
  'Mexican Rice and Beans': 'Tomato rice with seasoned beans',
  'Mexican Rice and Vegetables': 'Tomato rice with mixed vegetables',
  'Pork Fried Rice': 'Wok-fried rice with savory pork',
  'Vegetable Fried Rice': 'Wok-fried rice with vegetables',
  'Basmati Rice': 'Fragrant, long-grain basmati',
  'Vegetable Jambalaya': 'Cajun-spiced rice with vegetables',
  'Basmati Rice with Dill': 'Fragrant basmati with fresh dill',
  'Brown Rice with Vegetables and Tofu': 'Brown rice, vegetables and tofu',
  'Wild Rice with Vegetables and Tofu': 'Wild rice, vegetables and tofu',
  'Wild Rice with Edamame': 'Nutty wild rice, bright edamame',
  'Mexican Rice with Vegetables and Tofu': 'Tomato rice, vegetables and tofu',
  'Forbidden Rice with Vegetables and Tofu': 'Black rice, vegetables and tofu',
  'Vegetarian Paella': 'Saffron rice with seasonal vegetables',
  'Basmati Brown Rice with Dried Fruit': 'Brown basmati with dried fruit',
  'Basmati Rice with Cranberries, Dates and Apricots': 'Basmati with cranberries, dates, apricots',
  'Black Sticky Rice': 'Chewy, nutty black sticky rice',
  'Chicken Jambalaya': 'Cajun rice with chicken and peppers',
  'Coconut Basmati Rice': 'Basmati simmered in coconut milk',
  'Coconut Jasmine Rice': 'Jasmine rice with creamy coconut',
  'Farro': 'Nutty, chewy ancient grain',
  'Forbidden Rice': 'Nutty, deep-purple black rice',
  'Ginger Curried Fried Rice': 'Fried rice with ginger and curry',
  'Israeli Couscous': 'Pearl couscous with herbs',
  'Mahogany Steamed Black Rice': 'Steamed black rice, nutty and rich',
  'Pumpkin Risotto': 'Creamy arborio with roasted pumpkin',
  'Risotto with Cantaloupe': 'Creamy risotto with sweet cantaloupe',
  'Risotto ai Porcini': 'Creamy risotto with porcini mushrooms',
  'Spanish Paella with Shrimp and Free-Range Chicken': 'Saffron rice, shrimp and chicken',
  'Spanish Yellow Organic Rice with Veggies': 'Spanish saffron rice with vegetables',
  'Steamed Brown Rice': 'Wholesome, nutty steamed brown rice',
  'Veggie Couscous': 'Fluffy couscous with roasted vegetables',

  // ---- Chicken ----
  'Kung Pao Chicken': 'Spicy wok chicken with peanuts',
  'Orange Ginger Chicken': 'Crispy chicken in orange-ginger glaze',
  'Chicken and Broccoli': 'Wok chicken and broccoli, savory sauce',
  'Chicken Kabob': 'Marinated chicken skewers, flame-grilled',
  'Grilled Chicken Paillard with Tomatoes and Arugula': 'Thin grilled chicken, tomatoes, arugula',
  'Roasted Rosemary Chicken': 'Herb-roasted chicken with rosemary',
  'Free-Range Roasted Rosemary Chicken': 'Free-range chicken roasted with rosemary',
  'Chicken Parm': 'Breaded chicken, marinara, melted mozzarella',
  'Chicken Pot Pie': 'Creamy chicken and vegetables, flaky crust',
  'Chicken Fajita': 'Sizzling chicken, peppers and onions',
  'BBQ Chicken': 'Smoky chicken with tangy barbecue glaze',
  'Grilled Chicken Breasts with Grilled Veggies': 'Grilled chicken with charred vegetables',
  'Chicken Alfredo': 'Chicken in parmesan cream sauce',
  'Chicken Cacciatore': 'Braised chicken, tomatoes and mushrooms',
  'Chicken Chimichurri': 'Grilled chicken with bright herb sauce',
  'Chicken Cordon Bleu': 'Chicken rolled with ham and cheese',
  'Chicken Cutlets': 'Golden, crisp breaded chicken',
  'Chicken Marsala': 'Chicken with mushrooms in Marsala wine',
  'Chicken Piccata': 'Chicken with lemon, capers and olives',
  'Chicken Pizzaiola': 'Chicken in tomato, oregano and garlic',
  'Chicken Roulade with Prosciutto and Mozzarella': 'Chicken rolled with prosciutto, mozzarella',
  'Chicken Tikka Masala': 'Tandoori chicken in spiced tomato cream',
  'Chicken with Ginger and Veggies': 'Chicken stir-fried with ginger, vegetables',
  'Chicken with Prosciutto and Mozzarella': 'Chicken topped with prosciutto, mozzarella',
  'Chicken with Apricots, Shitake Mushrooms and Couscous': 'Chicken, apricots, shiitakes and couscous',
  'Dijon Chicken': 'Chicken in creamy Dijon sauce',
  'Fried Chicken': 'Crispy, golden buttermilk fried chicken',
  'Lemon Chicken': 'Tender chicken with bright lemon',
  'Moroccan Chicken': 'Chicken with warm Moroccan spices',
  'Pulled Chicken': 'Slow-cooked, tender shredded chicken',
  'Tarragon Chicken': 'Chicken in creamy tarragon sauce',
  'Chicken Fingers': 'Crispy, golden chicken tenders',
  'Teriyaki Chicken': 'Chicken glazed in sweet teriyaki',

  // ---- Beef / Pork ----
  'Braised Pork Ribs': 'Slow-braised, fall-off-the-bone ribs',
  'Sloppy Joe': 'Saucy seasoned beef, toasted bun',
  'Beef and Broccoli': 'Tender beef and broccoli, savory sauce',
  'Black Pepper Sirloin Steak': 'Seared sirloin with cracked black pepper',
  'Bourbon Braised Beef': 'Beef slow-braised with bourbon',
  'Tamari Shredded Pork': 'Tender pork glazed with tamari',
  'Vegetable, Chicken, Pork Dumplings': 'Steamed dumplings, three fillings',
  'Vegetable, Pork, Shrimp Spring Rolls': 'Crispy rolls, three fillings',
  'Grass-Fed Hamburgers': 'Juicy grass-fed beef burgers',
  'Kofta Kabob': 'Spiced ground meat skewers, grilled',
  'Home Made Meatloaf with Gravy': 'Classic meatloaf with rich gravy',
  'Meatloaf': 'Classic home-style meatloaf',
  'Braised Beef': 'Slow-braised, melt-in-your-mouth beef',
  'Seared Skirt Steak with Rosemary': 'Seared skirt steak, fresh rosemary',
  'Meatballs Marinara': 'Tender meatballs in marinara',
  'Carnitas': 'Slow-cooked, crisp-edged pulled pork',
  'Beef Taco': 'Seasoned beef with fresh toppings',
  'Beef Fajita': 'Sizzling steak, peppers and onions',
  'Hamburgers': 'Classic juicy beef burgers',
  'Beef Stew with Organic Potatoes and Carrots': 'Hearty beef stew, potatoes, carrots',
  'Brisket': 'Slow-cooked, tender sliced brisket',
  'Rib-Eye': 'Richly marbled, perfectly seared steak',
  'Filet Mignon in Hoisin Sauce': 'Tender filet with hoisin glaze',
  'Filet Mignon with Rosemary': 'Tender filet with fresh rosemary',
  'Swedish Meatballs': 'Meatballs in creamy savory gravy',
  'Marinated Sliced Skirt Steak': 'Marinated skirt steak, thinly sliced',
  "Shepherd's Pie": 'Savory meat under mashed potato',
  'Beef Tenderloin': 'Roasted, tender center-cut beef',
  'Filet with Balsamic Reduction': 'Filet with sweet balsamic glaze',
  'Prime Rib': 'Slow-roasted, juicy prime rib',
  'Texas Beef Chili': 'Hearty spiced beef chili',
  'Pork Chops': 'Juicy seared bone-in pork chops',
  'Pork Loin with Aromatic Spices': 'Spice-rubbed roasted pork loin',
  'Pork Loin with Mushrooms': 'Roasted pork loin, mushroom sauce',
  'Pulled Pork': 'Slow-smoked, tender pulled pork',
  'Roasted Rosemary Pork Loin': 'Pork loin roasted with rosemary',

  // ---- Fish ----
  'Seared Salmon with Spinach': 'Seared salmon over sautéed spinach',
  'Organic Seared Wild King Salmon with Spinach': 'Wild king salmon over spinach',
  'Seared Teriyaki Salmon with Bok Choy': 'Teriyaki salmon with tender bok choy',
  'Salmon Teriyaki': 'Salmon glazed in sweet teriyaki',
  'Miso Glazed Cod Fish with Bok Choy': 'Miso-glazed cod with bok choy',
  'Tilapia with Capers and Lemon': 'Tilapia with lemon and capers',
  'Mild Coconut Curry Fish': 'Flaky fish in mild coconut curry',
  'Chilean Sea Bass with Miso': 'Buttery sea bass, miso glaze',
  'Coconut Crusted Salmon': 'Salmon with crisp coconut crust',
  'Crab Cakes': 'Golden lump crab cakes',
  'Grilled Salmon with Lemon Butter and Capers': 'Grilled salmon, lemon butter, capers',
  'Mahi-Mahi': 'Mild, flaky grilled mahi-mahi',
  'Panko Crusted Salmon Fillets with Horseradish Sauce': 'Panko salmon with horseradish sauce',
  'Poached Salmon': 'Delicately poached salmon fillet',
  'Rosemary Infused Cod': 'Flaky cod with rosemary',
  'Sea Bass with Tomato and Capers': 'Sea bass, tomatoes and capers',
  'Seared Tuna': 'Sesame-seared rare tuna',
  "Slammin' Salmon (Cajun Spices)": 'Salmon blackened with Cajun spices',
  'Sweet Chili Salmon': 'Salmon with sweet chili glaze',
  'Tilapia Meuniere': 'Tilapia in lemon brown butter',
  'Tilapia with Chive Oil and Capers': 'Tilapia with chive oil, capers',
  'Tilapia with Corn Salsa': 'Tilapia topped with corn salsa',
  'Tuna Steaks': 'Grilled tuna steaks, simply seasoned',

  // ---- Vegetarian Main ----
  'Vegan Taco Meat (faux meats)': 'Seasoned plant-based taco filling',
  'Eggplant and Mushroom Fajitas': 'Sizzling eggplant, mushrooms and peppers',
  'Tofu Steaks with Hoisin Sauce': 'Seared tofu with hoisin glaze',
  'Impossible Burgers': 'Plant-based burgers, grilled juicy',
  'Black Bean Burgers': 'Hearty black bean patties',
  'Chana Masala': 'Chickpeas in spiced tomato gravy',
  'Falafel': 'Crispy herbed chickpea fritters',
  'Eggplant Parm': 'Breaded eggplant, marinara, mozzarella',
  'Black Bean Meatballs': 'Plant-based black bean meatballs',
  'BBQ Tofu': 'Tofu glazed in smoky barbecue',
  'Vegan Stuffed Tomatoes': 'Tomatoes filled with herbed grains',

  // ---- Vegetable ----
  'Organic Roasted Potatoes': 'Golden roasted potatoes with herbs',
  'Cauliflower in Garlic Sauce': 'Tender cauliflower, savory garlic sauce',
  'Eggplants with Garlic Sauce': 'Silky eggplant in garlic sauce',
  'Super Greens': 'Sautéed kale, chard and spinach',
  'Grilled Organic Bok Choy': 'Charred bok choy, light seasoning',
  'Vegetable Stir Fry': 'Crisp vegetables, wok-tossed',
  'Charro Beans': 'Pinto beans simmered with spices',
  'Crispy Brussels Sprouts': 'Roasted until crisp and caramelized',
  "Baked Potato Bar with the Fixin's": 'Baked potatoes with all the toppings',
  'Sauteed Portobello Mushrooms': 'Meaty portobellos sautéed with garlic',
  'Crispy Onions': 'Golden, crunchy fried onions',
  'Home-Made Potato Chips': 'Thin, crisp house-made chips',
  'Cumin-Roasted Cauliflower': 'Roasted cauliflower with toasted cumin',
  'Organic Grilled Vegetables': 'Seasonal vegetables, flame-grilled',
  'Fried Eggplants': 'Crispy golden eggplant slices',
  'Roasted Acorn Squash': 'Caramelized, tender roasted squash',
  'Roasted Butternut Squash': 'Sweet, caramelized butternut squash',
  'Grilled Organic Asparagus and Broccolini': 'Charred asparagus and broccolini',
  'Creamy Mashed Potatoes': 'Buttery, velvety whipped potatoes',
  'Mashed Potatoes': 'Classic smooth mashed potatoes',
  'Sauteed Broccoli': 'Tender broccoli sautéed in olive oil',
  'Sauteed Broccoli with Garlic': 'Broccoli sautéed with garlic',
  'Steamed Broccoli': 'Bright, tender steamed broccoli',
  'Collard Greens': 'Slow-cooked, savory Southern greens',
  'Carrots and Zucchini': 'Sautéed carrots and zucchini',
  'Roasted Baby Potatoes': 'Crisp baby potatoes with herbs',
  'Sweet Plantains': 'Caramelized, tender ripe plantains',
  'Black Beans': 'Seasoned, slow-simmered black beans',
  'Baked Sweet Potatoes': 'Tender, naturally sweet baked potatoes',
  'Baked Potatoes': 'Fluffy oven-baked potatoes',
  'Broccolini': 'Tender, slender broccolini',
  'Butternut Squash with Ricotta Salata': 'Roasted squash with salty ricotta',
  'Corn on the Cob': 'Sweet buttery corn on the cob',
  'Creamed Spinach': 'Spinach in rich, creamy sauce',
  'Creamy Parsnip Puree': 'Silky, sweet parsnip purée',
  'Crispy Kale': 'Oven-crisped, lightly salted kale',
  'Curried Cauliflower with Tahini': 'Curry-roasted cauliflower, tahini drizzle',
  'Grilled Asparagus': 'Charred asparagus with olive oil',
  'Grilled Zucchini': 'Smoky grilled zucchini',
  'Haricot Vert': 'Tender French green beans',
  'Lyonnaise Potatoes': 'Pan-fried potatoes with onions',
  'Mashed Sweet Potatoes': 'Creamy whipped sweet potatoes',
  'Potatoes Au Gratin': 'Layered potatoes in cheesy cream',
  'Refried Beans': 'Creamy, seasoned refried beans',
  'Roasted Brussels Sprouts': 'Caramelized roasted Brussels sprouts',
  'Roasted Cauliflower': 'Golden roasted cauliflower',
  'Roasted Heirloom Potatoes': 'Colorful heirloom potatoes, roasted',
  'Sauteed Broccoli Rabe': 'Garlicky, slightly bitter broccoli rabe',
  'Sauteed Kale': 'Tender kale sautéed with garlic',
  'Sauteed Onions and Peppers': 'Sweet sautéed onions and peppers',
  'Sauteed Spinach': 'Spinach wilted with garlic',
  'Smashed Potatoes': 'Crispy smashed potatoes with herbs',
  'Steak Fries': 'Thick-cut, golden steak fries',
  'Steamed Carrots': 'Tender, sweet steamed carrots',
  'Steamed Zucchini': 'Lightly steamed tender zucchini',
  'String Beans Almandine': 'Green beans with toasted almonds',
  'Stuffed Tomatoes with Minced Meat': 'Tomatoes filled with seasoned meat',

  // ---- Spread / Bread ----
  'Hard and Soft Taco Shells': 'Crunchy and soft taco shells',
  'Fresh Baked Breads with GF Options': 'Fresh breads, gluten-free available',
  'Guacamole, Salsa, Sour Cream, Shredded Cheese': 'Classic taco toppings bar',
  'Fresh Guacamole': 'Hand-mashed avocado, lime, cilantro',
  'Cheese Toppers: Blue, Cheddar, Mozzarella, Swiss': 'Four cheeses for topping',
  'Sliced Tomatoes, Onions and Pickles': 'Classic burger toppings',
  'Fresh Deli and Sliced Cheeses Selections': 'Sliced deli meats and cheeses',
  'Fresh Baked Sandwich Rolls, Buns and Brioche': 'Fresh rolls, buns and brioche',
  'Hummus, Tahini, Yogurt with Dill': 'Hummus, tahini and dill yogurt',
  'Hummus, Tahini, Tzatziki Spreads': 'Hummus, tahini and tzatziki',
  'Fresh Pita': 'Warm, soft pita bread',
  'Tortillas': 'Warm flour and corn tortillas',
  'Deli and Cheese Tray': 'Sliced deli meats and cheeses',
  'Fresh Deli and Cheese Tray': 'Sliced deli meats and cheeses',

  // ---- Dessert ----
  'Fresh Baked Cookies': 'Warm cookies, baked fresh daily',
  'Fresh Brownies': 'Fudgy, rich chocolate brownies',
  'Assorted Fruit': 'Seasonal fruit, freshly cut',
  'Rainbow Cake': 'Colorful layers with vanilla frosting',
  'Lemon Bars': 'Tangy lemon curd, buttery crust',
  'Chocolate Chip Cookies': 'Classic chewy chocolate chip',
  'Fresh Baked Sugar Cookies': 'Soft, sweet buttery sugar cookies',
  'Fresh Baked Crumb Cake': 'Buttery cake, brown-sugar crumble',
  'Brownies': 'Fudgy, rich chocolate brownies',
  'Chocolate Cake': 'Moist, rich chocolate layer cake',
  'Black Forest Cake': 'Chocolate, cherries and whipped cream',
  'Orange Cake': 'Moist cake with bright orange',
  'Mango Ice Cream': 'Creamy, tropical mango ice cream',
  'Sliced Watermelon': 'Sweet, juicy fresh watermelon',
  'Pineapple and Oranges': 'Fresh pineapple and orange segments',
  'Lychees': 'Sweet, floral fresh lychees',
  'Fresh Baked Blondies and Cookies': 'Buttery blondies and fresh cookies',
  'Fresh Berries with Mint': 'Seasonal berries with fresh mint',
  'Mango Rice Pudding': 'Creamy rice pudding with mango',
  'Cardamom-Spiced Fresh Fruit': 'Fresh fruit with warm cardamom',
  'Fresh Cookies': 'Warm cookies, baked fresh daily',
  'Fresh Cookies and Brownies': 'Fresh cookies and fudgy brownies',
  'Fresh Blondies and Brownies': 'Blondies and fudgy brownies',
  'Baklava': 'Flaky phyllo, honey and nuts',
  'French Macarons': 'Delicate almond meringue sandwich cookies',
  'Belgian Chocolate Cake': 'Decadent Belgian chocolate layers',
  'Limoncello Cake': 'Light lemon cake with limoncello',
  'Red Velvet Cake': 'Velvety cocoa cake, cream cheese frosting',
  'Cheesecake': 'Rich, creamy New York style',
  'Apple Pie': 'Spiced apples in flaky crust',
  'Blueberry Pie': 'Sweet blueberries in golden crust',
  'Berry Trifle': 'Layers of berries, cake and cream',
  'Chocolate Salted Caramel Trifle': 'Chocolate, salted caramel and cream',
  'Banana Cream Pie Trifle': 'Banana, vanilla custard and cream',
  'Flan': 'Silky caramel custard',
  'Tres Leches': 'Sponge cake soaked in three milks',
  'Fresh Fruit Tray': 'Seasonal fruit, beautifully arranged',
  'Alfajores': 'Dulce de leche sandwich cookies',
  'Fresh Pies': 'Seasonal pies, baked fresh',
  'Fresh Biscotti': 'Crunchy twice-baked Italian cookies',
  'Cannolis': 'Crisp shells, sweet ricotta filling',
  'Cannoli Cake': 'Layered cake with cannoli cream',
  'Chocolate Mousse Cake': 'Airy chocolate mousse on cake',
  'Coconut Macaroons': 'Chewy, golden coconut macaroons',
  'Crack Pie': 'Gooey, buttery oat-crust pie',
  'Cupcakes': 'Frosted cupcakes, assorted flavors',
  'Dulce de Leche Cake': 'Moist cake with caramel dulce',
  'Éclairs': 'Chocolate, Nutella and caramel éclairs',
  'French Almond Macaroons': 'Delicate almond macaroons',
  'Lemon Mousse Cake': 'Light, tangy lemon mousse cake',
  'Meringues with Whipped Cream': 'Crisp meringues with whipped cream',
  'Rose Water Rice Pudding': 'Creamy rice pudding, delicate rose',
  'Rugelach': 'Flaky rolled pastries, sweet fillings',
  'Home-Made Tiramisu': 'Espresso-soaked ladyfingers, mascarpone cream',
};
